### ISSUE TITLE
Error APPX0702 

### ISSUE THREAD

**Issue by ad87mb** [Microsoft/WinObjC#2179] opened 2017-03-08 09:08 UTC
Not exist. "....\Debug\Base.lproj\Main.Storyboardc" in Microsoft.AppXPackage.Targets

**Comment by ArnOmsft** [comment] 2017-03-09 21:47
Hi, can you describe what you're doing and when does this error show-up? Are you getting this when running vsimporter against your project?
Thanks.

**Comment by weswmsft** [comment] 2017-03-23 17:14
Can you please provide more details and explain how we can reproduce the bug?

**Comment by memontic-ms** [comment] 2017-04-04 00:14
Microsoft.AppXPackage.Targets looks like (app) build-time targets, so probably not vsimporter.

Could not reproduce this error.  Closing.

**Closed by memontic-ms** 2017-04-04 00:14 UTC
Labels: Area-Dev Tools, Bug, Triage-Investigate
