### ISSUE TITLE
Crash in CFPreferences _preferencesDirectoryForUserHostSafetyLevel

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#1787] opened 2017-01-24 12:44 UTC
We’re seeing many crashes with the following info. Unfortunately the actual stack trace leading up to the exception is not currently available to us, but the crash seems to be in [`_preferencesDirectoryForUserHostSafetyLevel()`](https://github.com/Microsoft/WinObjC/blob/7c86e9a1b94156491df2585b099f61ca48733774/Frameworks/CoreFoundation/Preferences.subproj/CFPreferences.c#L180).

```
NULL_POINTER_READ_c0000005_CoreFoundation.dll!preferencesDirectoryForUserHostSafetyLevel

Frame	Image	Function	Offset
0	ntdll	KiFastSystemCallRet	0x0
1	ntdll	NtWaitForMultipleObjects	0xA
2	kernelbase	WaitForMultipleObjectsEx	0x10A
3	kernelbase	WaitForMultipleObjects	0x18
4	kernel32	WerpReportFaultInternal	0x3FB
5	kernel32	WerpReportFault	0x68
6	kernel32	BasepReportFault	0x19
7	kernelbase	UnhandledExceptionFilter	0x1F4
8	ntdll	TppExceptionFilter	0x30
9	ntdll	TppWorkerpInnerExceptionFilter	0xE
10	ntdll	TppWorkerThread	0x69AF9
11	kernel32	BaseThreadInitThunk	0x24
12	ntdll	__RtlUserThreadStart	0x2B
13	ntdll	_RtlUserThreadStart	0x1B
```

We also found issue https://github.com/Microsoft/WinObjC/issues/1613#issuecomment-270933945 referencing the same function, but it’s unclear if this is the same root cause.

**Comment by rajsesh-msft** [comment] 2017-01-24 18:09
@triplef, thanks for reporting this.  Looking at the call stack, this indeed appears to be a dupe of #1613.  This would happen when creating preferences store where the user name is non-english and has accent or special characters.

**Closed** 2017-01-24 18:10 UTC
Labels: Area-Foundation, Bug, Resolution-Duplicate
