### ISSUE TITLE
[x86] [WOCCatalog] Text Missing in Text Display Mode Page

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#2649] opened 2017-04-28 16:49 UTC
UITextViews will scrollable text and CTLineCreateTruncatedLine are missing text.

**Comment by msft-Jeyaram** [comment] 2017-04-28 18:27
Taking a look at this

**Comment by msft-Jeyaram** [comment] 2017-04-28 21:21
The root cause is that the sample was written wrong.
You should be passing CGColor to CoreText, but the sample was passing UIColor. Thus it was not able to render it.

**Comment by rajsesh-msft** [comment] 2017-04-28 21:32
https://www.youtube.com/watch?v=JYc05gZFly0

**Comment by msft-Jeyaram** [comment] 2017-04-28 23:08
I'm working on it :)

![image](https://cloud.githubusercontent.com/assets/18413092/25550307/f47ec594-2c2c-11e7-9aac-061685b1615a.png)

**Comment by msft-Jeyaram** [comment] 2017-05-06 05:40
Closed as per #2662

**Closed by msft-Jeyaram** 2017-05-06 05:40 UTC
Labels: Area-User Experience, Bug
