### ISSUE TITLE
Error during build process

### ISSUE THREAD

**Issue by LenoreMarlow** [Microsoft/WinObjC#817] opened 2016-08-04 20:00 UTC
I am working on converting our application using the bridge.  I have removed all issues related to third party libs.  Upon running the Start without debugging get the following error related to a file that does not exist.   Can anyone explain this or know how to correct?

Error   LNK1181 cannot open input file 'Debug\Package_2A37E4F1.obj'

**Comment by rajsesh-msft** [comment] 2016-08-04 20:24
Hello, thanks for reporting the issue.  In order to help, could you please provide the build log by following these steps in our [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue)?  Thanks in advance!

**Comment by LenoreMarlow** [comment] 2016-08-04 20:45
Here is my log file. The file contrents were too large for the comment.
Thank you
[log.zip](https://github.com/Microsoft/WinObjC/files/402670/log.zip)

**Comment by asimonov-im** [comment] 2016-08-11 07:35
@LenoreMarlow Looking at the logs, it appears that your project's Package.appxmanifest is mislabeled as a ClangCompile item.

Please try the following:
1. Open your project in VS and locate Package.appxmanifest in Solution Explorer.
2. Right click on the item and select Properties.
3. Change the Item Type from "Clang source" to "App Package Manifest"

**Comment by LenoreMarlow** [comment] 2016-08-11 20:15
Thank you for your help.  I have made the following changes
 In Package.appxmanifest - Change the Item Type from "Clang source" to "App Package Manifest"
received the following errors
LNK1120	2 unresolved externals
LNK2001	unresolved external symbol __OBJC_CLASS_UIMenuController
LNK2019	unresolved external symbol __OBJC_CLASS_UIMenuItem referenced in function _-[TMAAppDelegateBase setupContextMenu]
LNK2019	unresolved external symbol __OBJC_CLASS_UIMenuController referenced in function _-[TMADisabledTextFieldRespondingView initiateContextMenu:]

**Comment by asimonov-msft** [comment] 2016-08-12 16:17
@LenoreMarlow It looks like our UIMenuController and UIMenuItem header files are missing the UIKIT_EXPORT_CLASS macro. Please try adding the macro to the relevant class interfaces (see [UIButton.h](https://github.com/Microsoft/WinObjC/blob/d9578b016df6cfc3822ff409904b69544a2a6ec6/include/UIKit/UIButton.h) for example) and rebuild.

Out of curiosity, why did you need to add msvcrt.lib and msvcmrt.lib to your project?

**Comment by LenoreMarlow** [comment] 2016-08-29 18:39
Hello, I apologize for not getting back to you sooner.  Deadlines for existing projects force me to put this project aside for a short while.  I added the msvcrt.lib and msvcmrt.lib to my project after researching a LINK 2001 error unresolved external symbol __OBJC_CLASS_UIMenuController.  I has several errors:
Error	LNK1120	2 unresolved externals	
Error	LNK2001	unresolved external symbol __OBJC_CLASS_UIMenuController	
Error	LNK2019	unresolved external symbol __OBJC_CLASS_UIMenuItem referenced in function _-[TMAAppDelegateBase setupContextMenu]	
Error	LNK2019	unresolved external symbol __OBJC_CLASS_UIMenuController referenced in function _-[TMADisabledTextFieldRespondingView initiateContextMenu:]

After researching the error I found this and chose to add the files.  Not sure if they are necessary.

Linker Tools Error LNK2001
Visual Studio 2015 
unresolved external symbol "symbol"
Code references something (such as a function, variable, or label) that the linker can't find in the libraries and object files.
This error message is followed by fatal error LNK1120.
Possible Causes
•	When upgrading a managed library or web service project from Visual C++ 2003, the /Zl compiler option is added to the Command Line property page. This will cause LNK2001. 

To resolve this error, either add msvcrt.lib and msvcmrt.lib to the linker's Additional Dependencies property. Or, remove /Zl from the Command Line property page. For more information, see /Zl (Omit Default Library Name) and How to: Open Project Property Pages. 


This lead to the next error:
I followed the recommendations on Microsoft website to omit the default libraries by do this:

To set this compiler option in the Visual Studio development environment
1.	Open the project's Property Pages dialog box. For details, see How to: Open Project Property Pages. 
2.	Click the C/C++ folder.
3.	Click the Advanced property page.
4.	Modify the Omit Default Library Names property.

After this I received the error:
LINK : fatal error LNK1104: cannot open file 'MSVCRTD.lib'

Go to your project properties, select Linker from left. Add this to "Additional Library Directories":
"(Your Visual Studio Path)\VC\lib"
This is where I added the libraries to the Additional Library Directories.

I now have other errors.  Maybe I should not leave the msvcrt.lib and msvcmrt.lib in my project.  I can removed them if this is recommended.  I'm really trying to launch this project to see if tI can use this to get to the windows platform.

I made the changes to the UIMenuController and UIMenuItem header files as specified.  My log is attached as I still cannot get it to successfully compile.
[log2.zip](https://github.com/Microsoft/WinObjC/files/443204/log2.zip)

**Comment by LenoreMarlow** [comment] 2016-08-30 20:25
I made the following changes after considering the response from asimonov-msft as to why I included the msvcrt files.

- Remove msvcrt.lib and msvcmrt.lib from Project Property Page/Linker/Additional Dependencies
- Remove msvcrt.lib and msvcmrt.lib from Project Property Page/Linker/ Ignore Specific Default Libraries
- Ignore All Default Libraries changed back to No

Now I have just 4 errors related to the UIMenuController and UIMeniItem.  Maybe I did not make the changes for UIKIT_EXPORT_CLASS correctly

1>------ Build started: Project: mobileTMAGOWin (MobileTMAGOWin\mobileTMAGOWin), Configuration: Debug Win32 ------
1>     Creating library C:\Bridge4iOS\mobileTMAGOWin\Debug\mobileTMAGOWin\mobileTMAGOWin.lib and object C:\Bridge4iOS\mobileTMAGOWin\Debug\mobileTMAGOWin\mobileTMAGOWin.exp
1>TMATextFieldGeneric_A33174D2.obj : error LNK2019: unresolved external symbol __OBJC_CLASS_UIMenuController referenced in function _-[TMADisabledTextFieldRespondingView initiateContextMenu:]
1>TMAAppDelegateBase_D61A9355.obj : error LNK2001: unresolved external symbol __OBJC_CLASS_UIMenuController
1>TMAAppDelegateBase_D61A9355.obj : error LNK2019: unresolved external symbol __OBJC_CLASS_UIMenuItem referenced in function _-[TMAAppDelegateBase setupContextMenu]
1>C:\Bridge4iOS\mobileTMAGOWin\Debug\mobileTMAGOWin\mobileTMAGOWin.exe : fatal error LNK1120: 2 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by antoine-haas** [comment] 2016-08-31 19:31
@LenoreMarlow, to make the change for UIKIT_EXPORT_CLASS just add the macro before the interface definition (as shown below) in the UIMenuController.h and UIMenuItem.h files, located under winobjc\include\UIKit.

UIMenuController:
```Objective-C
[...]
@class UIView, UIWindow;

UIKIT_EXPORT_CLASS // add the macro here
@interface UIMenuController : NSObject {
@private
[...]
```

UIMenuItem:
```Objective-C
[...]
#import <Foundation/Foundation.h>

UIKIT_EXPORT_CLASS // add the macro here
@interface UIMenuItem : NSObject {
@private
[...]
```

Do you still have the same errors after adding the macro?

**Comment by LenoreMarlow** [comment] 2016-08-31 21:38
Yes, made no difference. Will I need to run vsimporter again?  I am not sure if these files have been compiled into the project after running the importer or if I can just change the files in the winobjc folder.

**Comment by asimonov-msft** [comment] 2016-08-31 23:42
@LenoreMarlow I do not believe you need to re-run vsimporter. Please try doing a full rebuild of your project (after making the change to the UIKit header files).

An incremental build will not work, due to the fact that the module cache will not be regenerated.

**Comment by LenoreMarlow** [comment] 2016-09-01 19:55
After a full rebuild, I no longer get the errors.  I now have a few things to clean up and will update this thread with the status of the conversion to Bridges.

**Comment by LenoreMarlow** [comment] 2016-09-01 21:56
Last build, only 1 error. I attached the log file. I tried to decipher the log file and it looks like it could be something in the settings.

MSB3073	The command ""C:\winobjc\msvc\..\bin\Xib2Nib.exe" "..\..\GOTools\LinkedPhotosView_iphone.xib" "Debug\LinkedPhotosView_iphone.nib"" exited with code -1.	C:\winobjc\msvc\sbresources.targets
[log3.zip](https://github.com/Microsoft/WinObjC/files/450777/log3.zip)

**Comment by antoine-haas** [comment] 2016-09-02 18:24
@LenoreMarlow, the error above seems to be caused by an unsupported tag in your xib file. Could you share LinkedPhotosView_iphone.xib so that we can get a repro?

**Comment by LenoreMarlow** [comment] 2016-09-02 22:34
Yes. Here it is.  Thank you
[Linked Photos xib.zip](https://github.com/Microsoft/WinObjC/files/453010/Linked.Photos.xib.zip)

**Comment by antoine-haas** [comment] 2016-09-15 18:09
Hey @LenoreMarlow, sorry for the delay. It looks like the error is caused because you are using legacy xibs not supported by the bridge. We recommend upgrading your xibs by updating Xcode and opening your projects xibs in it, at which point Xcode should prompt you to upgrade them. If that doesn't work, you can also change the Interface Builder Document properties in the Xcode inspector for a xib file and then save the xib file again (as shown in the picture).
![ib properties](https://cloud.githubusercontent.com/assets/14913946/18561404/9129937e-7b34-11e6-90d4-404ce6f96b4f.png)

**Comment by LenoreMarlow** [comment] 2016-09-23 15:09
I was able to build the application without any errors. The result is that application loads extremely but when it opens, the screen is black.  No content, no errors.

[Log5.zip](https://github.com/Microsoft/WinObjC/files/489979/Log5.zip)

**Comment by antoine-haas** [comment] 2016-09-26 16:45
Are you using the latest release 0.2.160914 (September 14, 2016) of the bridge? If not, please try to build & run your app with it to see if the error persists.

**Comment by LenoreMarlow** [comment] 2016-09-28 21:28
After extracting the new build, I replaced my original winobjc folder with the new one.  I had to copy libiconv.dll, libiconv.lib, UIMenuController.h and UIMenuItem.h from the original.  Rebuild the app and it fails. libiconv.dll, libiconv.lib I rebuilt in the original and they worked, the one from the new build generated errors. The UIMenuController.h and UIMenuItem.h file from the new build were still missing the UIKIT_EXPORT_CLASS so I copied those as well.

From the log file:
Creating library C:\Bridge4iOS\mobileTMAGOWin\Debug\mobileTMAGOWin\mobileTMAGOWin.lib and object C:\Bridge4iOS\mobileTMAGOWin\Debug\mobileTMAGOWin\mobileTMAGOWin.exp (TaskId:78)
16:14:26.522     1>App.xaml.obj : error LNK2019: unresolved external symbol _EbrApplicationActivated referenced in function "protected: virtual void __cdecl mobileTMAGOWin::App::[Windows::UI::Xaml::IApplicationOverrides]::OnActivated(struct Windows::ApplicationModel::Activation::IActivatedEventArgs ^)" (?OnActivated@?QIApplicationOverrides@Xaml@UI@Windows@@App@mobileTMAGOWin@@M$AAAXP$AAUIActivatedEventArgs@Activation@ApplicationModel@4@@Z)
16:14:26.523     1>App.xaml.obj : error LNK2019: unresolved external symbol _EbrApplicationLaunched referenced in function "protected: virtual void __cdecl mobileTMAGOWin::App::[Windows::UI::Xaml::IApplicationOverrides]::OnLaunched(class Windows::ApplicationModel::Activation::LaunchActivatedEventArgs ^)" (?OnLaunched@?QIApplicationOverrides@Xaml@UI@Windows@@App@mobileTMAGOWin@@M$AAAXP$AAVLaunchActivatedEventArgs@Activation@ApplicationModel@4@@Z)
16:14:26.528     1>C:\Bridge4iOS\mobileTMAGOWin\Debug\mobileTMAGOWin\mobileTMAGOWin.exe : fatal error LNK1120: 2 unresolved externals
                     The command exited with code 1120. (TaskId:78)
                     Output Property: LinkSkippedExecution=False (TaskId:78)
                   Done executing task "Link" -- FAILED. (TaskId:78)
16:14:26.619     1>Done building target "Link" in project "mobileTMAGOWin.vcxproj" -- FAILED.: (TargetId:135)
16:14:26.619     1>Done Building Project "C:\Bridge4iOS\mobileTMAGOWin\MobileTMAGOWin.vsimporter\mobileTMAGOWin-WinStore10\mobileTMAGOWin.vcxproj" (Rebuild target(s)) -- FAILED.

**Comment by antoine-haas** [comment] 2016-09-28 23:04
This might be caused by a change in vsImporter. Please re-run vsImporter on your project with the new version of the SDK, instead of just replacing the winobjc folder.

**Comment by LenoreMarlow** [comment] 2016-09-29 20:56
My application is now building with no errors and the launch opens to a blank screen.  When debugging I am getting Source file not found - nsthread.mm not found. Do I need to include the winobjc folder 

 here are the details.
Locating source for 'd:\build\agent3\_work\14\s\frameworks\foundation\nsthread.mm'. (No checksum.)
The file 'd:\build\agent3\_work\14\s\frameworks\foundation\nsthread.mm' does not exist.
Looking in script documents for 'd:\build\agent3\_work\14\s\frameworks\foundation\nsthread.mm'...
Looking in the projects for 'd:\build\agent3\_work\14\s\frameworks\foundation\nsthread.mm'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cvt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\msclr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sys\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\amd64\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\arm\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\concrt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\i386\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\linkopts\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\stl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\vcruntime\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\mfc'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\mfcm'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\atl'...
Looking in directory ''...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Source\10.0.10240.0\ucrt'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\8.1\Include\um'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\8.1\Include\shared'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\8.1\Include\winrt'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Source\10.0.10586.0\ucrt'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\shared'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\winrt'...
Looking in directory 'C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\Include\um'...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: d:\build\agent3\_work\14\s\frameworks\foundation\nsthread.mm.
The debugger could not locate the source file 'd:\build\agent3\_work\14\s\frameworks\foundation\nsthread.mm'.

**Comment by antoine-haas** [comment] 2016-09-30 18:21
The error above is normal: the prebuilt SDK package doesn't contain the SDK sources, in particular nsthread.mm. You can get the source file by cloning the repo which contain all the sources, but I believe you shouldn't have to step into Foundation code to diagnose your issue.

**Comment by LenoreMarlow** [comment] 2016-10-10 22:49
It looks like things are working somewhat.  The emulator is opening, code is running however, it cannot establish a persistentStoreCoordinator.  I am lost looking at the log file to determine the problem. I see many files showing as deprecated, managedObjectContext.  This is worrying me a bit,.  After all this work, it the sqlite database is not supported what are my options?

[Log6.zip](https://github.com/Microsoft/WinObjC/files/520560/Log6.zip)

**Comment by rajsesh-msft** [comment] 2016-10-10 23:01
@LenoreMarlow we don't currently have support for CoreData, which explains why persistent store coordinator and ManagedObjectContext are not available.  

SQLLite is indeed supported, but CoreData is not.

**Comment by LenoreMarlow** [comment] 2016-10-11 15:48
How extensive would it be to replace the use of core data and the MOC?  I have seen several posts refering to implementing core data but do not see any progress.  this is a show stopper without a viable replacement or a supported implementation.

**Comment by rajsesh-msft** [comment] 2016-12-16 20:23
@LenoreMarlow unfortunately there aren't any easy choices to replace core data driven UI application.  Cocotron has an implementation of core data that may work for you.  (you could build it on top of your fork of winobjc).  Coredata is certainly in our sights, but we have had to look at other priorities in the short term that would help graphics intensive apps, so this is not in the immediate future.

**Comment by LenoreMarlow** [comment] 2016-12-19 15:15
Thank you so much for your response.  I appreciate you letting me know that core data is in your sites for sometime in the future.  I do understand that it would be a tremendous undertaking to tackle core data.  I will look into Cocotron as we are still looking for a faster implementation of our enterprise iPad product written in XCode to be available on windows platform.  Please keep me posted or let me know how to get updates on any future development for core data.  Thank you Rajsesh
Be well and happy holidays!

**Comment by rajsesh-msft** [comment] 2017-01-04 19:48
closing this issue as we have other issues tracking core data.  Thanks @LenoreMarlow!

**Closed by rajsesh-msft** 2017-01-04 19:48 UTC
Labels: Area-Dev Tools, Bug

**Comment by sriranjanr** [comment] 2017-10-12 17:25
@LenoreMarlow  I am getting the same linker LNK2019 problem

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _UIApplicationActivated referenced in function "protected: virtual void __cdecl aurioTouch::App::[Windows::UI::Xaml::IApplicationOverrides]::OnActivated(struct Windows::ApplicationModel::Activation::IActivatedEventArgs ^)" (?OnActivated@?QIApplicationOverrides@Xaml@UI@Windows@@App@aurioTouch@@M$AAAXP$AAUIActivatedEventArgs@Activation@ApplicationModel@4@@Z)	aurioTouch (aurioTouch\aurioTouch)	C:\Users\user\Downloads\aurioTouch\aurioTouch.vsimporter\aurioTouch-WinStore10\App.xaml.obj	1	
Error	LNK2019	unresolved external symbol _UIApplicationLaunched referenced in function "protected: virtual void __cdecl aurioTouch::App::[Windows::UI::Xaml::IApplicationOverrides]::OnLaunched(class Windows::ApplicationModel::Activation::LaunchActivatedEventArgs ^)" (?OnLaunched@?QIApplicationOverrides@Xaml@UI@Windows@@App@aurioTouch@@M$AAAXP$AAVLaunchActivatedEventArgs@Activation@ApplicationModel@4@@Z)	aurioTouch (aurioTouch\aurioTouch)	C:\Users\user\Downloads\aurioTouch\aurioTouch.vsimporter\aurioTouch-WinStore10\App.xaml.obj	1	
Error	LNK1120	2 unresolved externals	aurioTouch (aurioTouch\aurioTouch)	C:\Users\user\Downloads\aurioTouch\Debug\aurioTouch\aurioTouch.exe	1	

Could some one tell me how to solve this.I am a newbie to winobjc and just installed vs2017 and I am trying to get simple IOS apps to run.
