### ISSUE TITLE
[IslandwoodNews] Debug assert selecting "Local" from options menu

### ISSUE THREAD

**Issue by kellymor** [Microsoft/WinObjC#2065] opened 2017-02-23 20:44 UTC
Install Islandwood news from release drop share
Open Islandwood news
Select the Options (hamburger) menu
Select the "Local" item

Expected Result:
Only local news items are displayed

Actual Result:
Debug assert - classId != nil.  See history for full assertion with source and line number.

**Comment by ashvarma** [comment] 2017-02-23 22:21
This is a duplicate of #1977

**Comment by ashvarma** [comment] 2017-02-23 22:21
sorry I meant #1975

**Closed by ashvarma** 2017-02-23 22:21 UTC
