### ISSUE TITLE
VsImporter does not import header

### ISSUE THREAD

**Issue by weswmsft** [Microsoft/WinObjC#2122] opened 2017-03-01 17:47 UTC
When importing AFNetworking the 1)	objc/block_runtime.h doesn’t get imported automatically and so it is currently not working with modules turned on.

**Comment by memontic-ms** [comment] 2017-04-17 21:50
blocks_runtime.h is getting into the WinObjC.Language package correctly but it can't be found correctly with modules enabled. This needs a change in libobjc2: either an addition to libobjc2's modulemap or an additional include somewhere in libobjc2's headers.

**Comment by DHowett-MSFT** [comment] 2017-04-17 21:58
This is a duplicate of #1976.

**Comment by memontic-ms** [comment] 2017-04-18 00:21
### Repro
In a file with options 
```
<CompileAs>CompileAsObjCpp</CompileAs>
<ObjectiveCModules>true</ObjectiveCModules>
```
And the import
```
#import <objc/blocks_runtime.h>
```
The following will not compile because a definition for Block_copy cannot be found
```
void* info;
Block_copy(info);
```

**Closed** 2017-04-18 17:41 UTC
Labels: Area-Dev Tools, Bug, Triage-Investigate
