### ISSUE TITLE
NSURL fileURLWithPathComponents returns path related to Debug or Release folder

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1994] opened 2017-02-17 12:43 UTC
Hi.
Please take a look at the code snippet below:

```
// returns ./Documents  ,
// some time ago it was returning 
// C:\\Users\\<user name>\\AppData\\Local\\Packages\\<app_id>\\LocalState/Documents"

NSString *defaultPath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject]; 
NSLog(@"defaultPath  %@", defaultPath );

// returns "C:/Users/<path_to_the_app>/Debug/<App name>/AppX/Documents/test.txt"
//or "C:/Users/<path_to_the_app>/Release/<App name>/AppX/Documents/test.txt"
// some time ago it was returning 
// C:\\Users\\<user name>\\AppData\\Local\\Packages\\<app_id>\\LocalState\Documents\test.txt"

NSArray *pathComponents = [NSArray arrayWithObjects:defaultPath,@"test.txt", nil];
NSURL *fileUrl= [NSURL fileURLWithPathComponents:pathComponents];
NSLog(@"url path: %@", fileUrl.path);
```

**Comment by DHowett-MSFT** [comment] 2017-02-17 17:24
@rajsesh-msft this may be a regression from a60098da397d0a4aa39e213866bc5d1c41d4503c; the Path Mapper is returning the application root instead of the writable path root for `./`

**Comment by rajsesh-msft** [comment] 2017-02-22 01:27
path mapper doesnt (and never did) use application root path anywhere.  This is probably something else.

**Comment by rajsesh-msft** [comment] 2017-02-22 02:40
@jboich, I just tried this code from a test app (added the line to foundation test app) and got the correct folder name.  The writeable folder path is set during app initialization, and if it is set correctly.

**Comment by rajsesh-msft** [comment] 2017-02-22 02:47
@jboich did you perhaps sync to 8bbd30f739343b5afa73e63a33583cfda10eaf4d?  This change did regress the behavior, but it has since been fixed.  You may want to sync to HEAD from master (or at least sync up to   682ac5207f63ed96641e689ec5f6ab428dd4ac35.

**Comment by rajsesh-msft** [comment] 2017-02-22 17:57
Closing this issue out as this was an intermittent regression we had in develop that has since been fixed.  please re-open if this happens after you sync up to 682ac5207f63ed96641e689ec5f6ab428dd4ac35.

**Closed by rajsesh-msft** 2017-02-22 17:57 UTC
Labels: Area-Foundation, Blocking, Bug, Resolution-No Repro
