### ISSUE TITLE
XAMLCatalog custom text view AVs

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1910] opened 2017-02-02 23:31 UTC
Repro:
1) Open XAMLCatalog
2) Custom Text View
3) Type anything into the box

This repros in develop as of the CGD2D merge (#1892). However, I was using this as a test scenario until fairly late into CGD2D, so I suspect that the change that caused this was a part of the last merge from develop to CGD2D (#1889).

**Comment by oliversa-msft** [comment] 2017-02-10 23:36
Investigating

**Comment by oliversa-msft** [comment] 2017-02-11 01:55
We have a root cause and a fix for that issue in the projection. However, we are trying to find a band aid in the mean time as well until the projection fix can be made.

**Comment by oliversa-msft** [comment] 2017-02-11 02:13
Hmmm, the band of unsafe_unretained didn't work; might need to address #1950 earlier if there are few alternatives.

**Comment by tadam-msft** [comment] 2017-02-13 17:31
Resolving as a duplicate of 1950

**Closed by tadam-msft** 2017-02-13 17:31 UTC
Labels: Area-User Experience, Bug, Priority-Urgent, Resolution-Duplicate, Triage-Investigate
