### ISSUE TITLE
SecCertificateCopyData function unimplemented and is hindering the use of AFNetworking 3.1.0 evaluate authentication along with certificate  process.

### ISSUE THREAD

**Issue by venkatkongara** [Microsoft/WinObjC#2029] opened 2017-02-22 20:03 UTC
/**
@Status Stub
*/
CFDataRef SecCertificateCopyData(SecCertificateRef certificate) {
    UNIMPLEMENTED();
    return nullptr;
}

**Comment by rajsesh-msft** [comment] 2017-02-23 02:35
Duplicate of #1281

**Closed by rajsesh-msft** 2017-02-23 02:35 UTC
