### ISSUE TITLE
nugetized packages do not work properly with dev15.3

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#2782] opened 2017-08-17 15:40 UTC
I made checkout of the latest **master** branch of the WinObjC and I follow [Building From Source](https://github.com/Microsoft/WinObjC/wiki/Building-From-Source) instructions. But I get errors when trying to build the solution.
Please take a look at the screenshot attached.

![winobjc_master_build_error copy](https://user-images.githubusercontent.com/22300615/29420459-eb5e344c-8369-11e7-9d57-ae81b9b20ec6.PNG)

If I use **develop** branch I get lots of errors in powershell when performing this command:
` .\.tools\nuget.exe restore .\build\build.sln`

![winobjc_error_master copy](https://user-images.githubusercontent.com/22300615/29420701-a1a5e8ee-836a-11e7-8eae-a41911b61975.PNG)

I use latest Visual Studio 2017 (Community) version 15.3

**Comment by DHowett-MSFT** [comment] 2017-08-17 16:25
Hi @jboich! Sorry about the issue. I ran into this locally as well and escalated as appropriate.

I'll keep this thread updated.

As a workaround, 15.2 should suffice to keep you building. I know that's not the best answer! 🙂

**Comment by ms-jihua** [comment] 2017-08-18 21:10
Hi @jboich,

@DHowett-MSFT seems to have actually run into a slightly different issue from yours, and I am having trouble reproing the issue myself. If you haven't already, could I ask you to try the following steps as a basic sanity check?

`git clean -dfx
.\init.cmd
.\.tools\nuget.exe update -self
.\.tools\nuget.exe locals all -clear
.\.tools\nuget.exe restore .\build\build.sln`

**Comment by ms-jihua** [comment] 2017-08-18 22:15
Ignore what I just said, just found something interesting.

**Comment by ms-jihua** [comment] 2017-08-18 23:04
@jboich It appears this was caused by an infra failure on our end. While we are resolving this, you should be able to work around the nuget restore issue by building tools\tools.sln before building build\build.sln.

**Comment by jboich** [comment] 2017-08-19 23:08
Hi, all. Thanks a million for a feedback. I will try this on Monday, because I have limit access to the machine where I reproduce the issue.

**Comment by rajsesh-msft** [comment] 2017-08-21 16:46
@jboich could you share the build logs from the build step?  You should be able to safely ignore the build failures in the tools project.

**Comment by ms-jihua** [comment] 2017-08-22 22:45
@jboich I'm still working through the infra issue on our end. For tools.sln, you ought to be able to work around the build errors by nuget restoring and building from the command line instead of inside VS. Let me know if this doesn't work.

**Comment by bbowman** [comment] 2017-08-22 23:43
I am seeing new pre-release packages that meet the requirements in the screenshot `WinObjC.Language >= 0.2.170610` so @jboich you might try building build.sln from **develop** again.

**Comment by jboich** [comment] 2017-08-23 12:02
Hi, @bbowman. I was able to build **build.sln** from **develop** branch successfully.
Thanks a million to everyone for help!

**Comment by rajsesh-msft** [comment] 2017-11-18 01:04
This is now fixed, all projects build and work well with 15.4 (back compat with 15.3 isn't possible because of bugs in 15.3).

**Closed by rajsesh-msft** 2017-11-18 01:04 UTC
