### ISSUE TITLE
Conversion app with WKWebView

### ISSUE THREAD

**Issue by paskur** [Microsoft/WinObjC#2881] opened 2018-07-02 09:23 UTC
I can't convert my app with WKWebView from WebKit framework, it works when i replace this with deprecated UIWebView. Is that mean I cannot convert WKWebView to UWP, because it is not supported yet?

**Comment by edvv** [comment] 2018-07-02 12:16
@paskur This is a dup of this: https://github.com/Microsoft/WinObjC/issues/2376 which defines the answer.

**Comment by MSFTFox** [comment] 2018-07-03 23:01
As @edvv mentioned, this is a duplicate of #2376

**Closed as completed by MSFTFox** 2018-07-03 23:01 UTC
Labels: duplicate
