### ISSUE TITLE
Since two weeks my app in shown upside down

### ISSUE THREAD

**Issue by mgoemmel** [Microsoft/WinObjC#520] opened 2016-05-27 12:27 UTC
Any hints where I should have a look. I haven't read about any changes in areas which would explain this.

My app in a landscape only app. Playing with the values in

    mode.operationMode = WOCOperationModeTablet;
    mode.presentationTransform= UIInterfaceOrientationLandscapeRight;

does not change anything.

Thanks for any idea
Markus

**Comment by ehren** [comment] 2016-05-27 13:07
Possibly related to the change in ~ipad bundle loading.

Does the Info.plist of your target contain something like:

```
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationLandscapeRight</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
    </array>
```

(my app is set up as portrait on iphone and landscape on iPad)

Try changing it too:

```
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
       <string>UIInterfaceOrientationPortrait</string>
   </array>
```

I also have a landscape only tablet app. I've found that the Winobjc handling of UIInterfaceOrientationLandscapeRight (to just apply a rotation transform), does not work properly (resulting in improperly rotated app).

However, UIInterfaceOrientationPortrait has worked since the beginning (with my _landscape_ app).

So possibly, with the change in bundle loading, winobjc is now picking up the ~ipad specific interface orientation from your plist and applying the rotation transform which causes problems.

However, I would expect that if the issue is due to ~ipad resource loading, removing the 

```mode.operationMode = WOCOperationModeTablet;```

should resolve the issue - so perhaps there's something else going on.

fyi, this is my setup for a landscape only tablet app that seems to be working fairly well:

```
    mode.fixedWidth = 1024.0f;
    mode.fixedHeight = 768.0f;
    mode.fixedAspectRatio = 0.0f;
    mode.magnification = 1.0f;
    mode.autoMagnification = YES;
    mode.operationMode = WOCOperationModeTablet;
```

(with the UISupportedInterfaceOrientations set in the plist as UIInterfaceOrientationPortrait)

**Comment by ArnOmsft** [comment] 2016-06-24 03:41
@mgoemmel, did you have the chance to try the suggestion from ehren?
Thanks.

**Comment by mgoemmel** [comment] 2016-06-24 10:49
I've tried it, but it doesn't work. It seems that there is a problem in the framework. But I didn't find time so far to investigate into it. The last git pull version did not even run my app, so I have to look into this new problem first. I will check it during the next 2-3 days and will add my result here.

Thanks for your interest!

Markus

**Comment by mgoemmel** [comment] 2016-06-24 12:32
Well, after checking again, it works when I set

mode.presentationTransform= UIInterfaceOrientationLandscapeLeft;

So all is well here. You can close this thread.

Thanks
Markus

**Comment by ArnOmsft** [comment] 2016-06-24 16:57
Cool. Thank you for trying this and sending an update, closing now.

**Closed by ArnOmsft** 2016-06-24 16:57 UTC
Labels: Under Review
