### ISSUE TITLE
TextDrawing tests are consistently failing

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#2282] opened 2017-03-20 23:45 UTC
These CoreGraphics.Drawing.UnitTests.dll tests are consistently failing on my machine -- latest develop with no local changes – is anyone else seeing this?

Non-passing Tests:

    TestDrawingTextWithTransformedMatrices_Transform::Test [Failed]
        TestDrawingTextWithTransformedMatrices_Transform.TestMatrices/11 [Failed]
    TextDrawing_TextDrawingMode::Test [Failed]
        TextDrawing_TextDrawingMode.CGTextDrawingMode/15 [Failed]
        TextDrawing_TextDrawingMode.CGTextDrawingMode/16 [Failed]
        TextDrawing_TextDrawingMode.CGTextDrawingMode/17 [Failed]
        TextDrawing_TextDrawingMode.CGTextDrawingMode/21 [Failed]
        TextDrawing_TextDrawingMode.CGTextDrawingMode/22 [Failed]
        TextDrawing_TextDrawingMode.CGTextDrawingMode/23 [Failed]

Summary: Total=2797, Passed=2788, Failed=9, Blocked=0, Not Run=0, Skipped=0

**Comment by msft-Jeyaram** [comment] 2017-03-20 23:58
@DHowett-MSFT indicated that he ran them locally and the tests passed.

Seeing the outputs, it looks like our image diff might not be doing it's job.
Investigating further.
Expected:

![000001_ endmode overlappedrects_0_testimage cgcontext blending_kcgblendmodemultiply](https://cloud.githubusercontent.com/assets/18413092/24126957/53c2ef98-0d8e-11e7-8b51-cac79d1926c3.png)


Rendered:
![000002_ endmode overlappedrects_0_testimage cgcontext blending_kcgblendmodemultiply](https://cloud.githubusercontent.com/assets/18413092/24126959/598ffd80-0d8e-11e7-8770-aeac3378960f.png)


Diff:
![000003_ endmode overlappedrects_0_greenline testimage cgcontext blending_kcgblendmodemultiply](https://cloud.githubusercontent.com/assets/18413092/24126960/5d1bbce6-0d8e-11e7-8a11-f64358f4cb45.png)

**Comment by msft-Jeyaram** [comment] 2017-03-21 00:00
@jaredhms  Passing this onto AJ as worked on these.

**Comment by aballway** [comment] 2017-03-21 00:21
I'm unable to repro this locally, how are you running these tests?

**Comment by jaredhms** [comment] 2017-03-21 00:32
Either via run-unittests.ps1, or just running the tests with te.exe.  Can I share any test output with you?

**Comment by aballway** [comment] 2017-03-21 00:38
Yes please, there should be the errors logged in the output

**Comment by jaredhms** [comment] 2017-03-21 17:08
StartGroup: TestDrawingTextWithTransformedMatrices_Transform.TestMatrices/11
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1024> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1024> >], Line: 142]
Error: images differ nontrivially with
Error: 1084
Error:  registered differences:

![000001_ transform testmatrices_11_testimage testdrawingtextwithtransformedmatrices_transform testmatrices_11](https://cloud.githubusercontent.com/assets/13719817/24159957/caec2e1a-0e1d-11e7-9ee0-c890cbc6001c.png)
![000002_ transform testmatrices_11_testimage testdrawingtextwithtransformedmatrices_transform testmatrices_11](https://cloud.githubusercontent.com/assets/13719817/24159958/caed7554-0e1d-11e7-9222-ca444ceb2efa.png)
![000003_ transform testmatrices_11_greenline testimage testdrawingtextwithtransformedmatrices_transform testmatrices_11](https://cloud.githubusercontent.com/assets/13719817/24159959/caf25bd2-0e1d-11e7-979b-ad9e6ecf8125.png)

StartGroup: TextDrawing_TextDrawingMode.CGTextDrawingMode/15
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1> >], Line: 142]
Error: images differ nontrivially with
Error: 60
Error:  registered differences
![000003_ mode cgtextdrawingmode_15_greenline testimage textdrawingmode 5 0](https://cloud.githubusercontent.com/assets/13719817/24160030/110b4aa2-0e1e-11e7-9968-9a30bb8ab45a.png)
![000001_ mode cgtextdrawingmode_15_testimage textdrawingmode 5 0](https://cloud.githubusercontent.com/assets/13719817/24160031/11128592-0e1e-11e7-916c-81fee7e94176.png)
![000002_ mode cgtextdrawingmode_15_testimage textdrawingmode 5 0](https://cloud.githubusercontent.com/assets/13719817/24160029/110b4552-0e1e-11e7-9005-8d519b3a531e.png)

StartGroup: TextDrawing_TextDrawingMode.CGTextDrawingMode/16
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1> >], Line: 142]
Error: images differ nontrivially with
Error: 175
Error:  registered differences
![000004_ mode cgtextdrawingmode_16_testimage textdrawingmode 5 45](https://cloud.githubusercontent.com/assets/13719817/24160055/21eb0fb0-0e1e-11e7-90e8-e9edf445000d.png)
![000005_ mode cgtextdrawingmode_16_testimage textdrawingmode 5 45](https://cloud.githubusercontent.com/assets/13719817/24160054/21ea92ce-0e1e-11e7-8d9a-ac66ee8e6637.png)
![000006_ mode cgtextdrawingmode_16_greenline testimage textdrawingmode 5 45](https://cloud.githubusercontent.com/assets/13719817/24160057/21f1def8-0e1e-11e7-83c3-5bb5f221da01.png)

StartGroup: TextDrawing_TextDrawingMode.CGTextDrawingMode/17
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1> >], Line: 142]
Error: images differ nontrivially with
Error: 299
Error:  registered differences
![000009_ mode cgtextdrawingmode_17_greenline testimage textdrawingmode 5 -30](https://cloud.githubusercontent.com/assets/13719817/24160072/2abe96e8-0e1e-11e7-8e4a-875246960801.png)
![000007_ mode cgtextdrawingmode_17_testimage textdrawingmode 5 -30](https://cloud.githubusercontent.com/assets/13719817/24160070/2aaddd3a-0e1e-11e7-8d56-be1079775b4a.png)
![000008_ mode cgtextdrawingmode_17_testimage textdrawingmode 5 -30](https://cloud.githubusercontent.com/assets/13719817/24160071/2ab3ef0e-0e1e-11e7-9d83-ba0c15ed0fb9.png)

StartGroup: TextDrawing_TextDrawingMode.CGTextDrawingMode/21
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1> >], Line: 142]
Error: images differ nontrivially with
Error: 7
Error:  registered differences
![000012_ mode cgtextdrawingmode_21_greenline testimage textdrawingmode 7 0](https://cloud.githubusercontent.com/assets/13719817/24160089/332269a4-0e1e-11e7-8162-df0885d302c9.png)
![000010_ mode cgtextdrawingmode_21_testimage textdrawingmode 7 0](https://cloud.githubusercontent.com/assets/13719817/24160088/332214a4-0e1e-11e7-869e-cabd5106dbcc.png)
![000011_ mode cgtextdrawingmode_21_testimage textdrawingmode 7 0](https://cloud.githubusercontent.com/assets/13719817/24160090/33248798-0e1e-11e7-9278-4453fb672fbb.png)

StartGroup: TextDrawing_TextDrawingMode.CGTextDrawingMode/22
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1> >], Line: 142]
Error: images differ nontrivially with
Error: 17
Error:  registered differences
![000015_ mode cgtextdrawingmode_22_greenline testimage textdrawingmode 7 45](https://cloud.githubusercontent.com/assets/13719817/24160103/3b5cb854-0e1e-11e7-8ff7-da6d8b1dca8e.png)
![000013_ mode cgtextdrawingmode_22_testimage textdrawingmode 7 45](https://cloud.githubusercontent.com/assets/13719817/24160104/3be60c9e-0e1e-11e7-895d-f7322fe10c6e.png)
![000014_ mode cgtextdrawingmode_22_testimage textdrawingmode 7 45](https://cloud.githubusercontent.com/assets/13719817/24160102/3b3c391c-0e1e-11e7-8416-9a1b08615818.png)

StartGroup: TextDrawing_TextDrawingMode.CGTextDrawingMode/23
Error: Failed [File: I:\enl\vso_2_WinObjC\tests\unittests\CoreGraphics.Drawing\DrawingTest.cpp, Function: virtual void testing::DrawTest<PixelByPixelI
mageComparator<PixelComparisonModeMask<1> > >::PostDraw() [TComparator = PixelByPixelImageComparator<PixelComparisonModeMask<1> >], Line: 142]
Error: images differ nontrivially with
Error: 15
Error:  registered differences
![000017_ mode cgtextdrawingmode_23_testimage textdrawingmode 7 -30](https://cloud.githubusercontent.com/assets/13719817/24160131/45abbdd2-0e1e-11e7-919c-1ff50d21d5bd.png)
![000018_ mode cgtextdrawingmode_23_greenline testimage textdrawingmode 7 -30](https://cloud.githubusercontent.com/assets/13719817/24160124/43b14736-0e1e-11e7-9e0f-889ae08df076.png)
![000016_ mode cgtextdrawingmode_23_testimage textdrawingmode 7 -30](https://cloud.githubusercontent.com/assets/13719817/24160126/43c86312-0e1e-11e7-86ba-8c9215642c7e.png)

**Comment by aballway** [comment] 2017-03-21 17:44
Mmmk so these seem to be related to #2107.  Your system probably has slightly different antialiasing settings that are just enough off to trip the threshold on the first test.  The rest don't yet have a threshold so we could just add a small threshold to those.

**Comment by rajsesh-msft** [comment] 2017-03-21 19:41
@jaredhms what windows build are you on + do you have cleartype enabled?

**Comment by jaredhms** [comment] 2017-03-21 19:47
ClearType is on; running Windows build 15063.rs2_release_dep.170317-1912

**Comment by rajsesh-msft** [comment] 2017-03-24 17:40
Resolving it as dupe of #2107.

**Closed by rajsesh-msft** 2017-03-24 17:40 UTC
Labels: Area-Foundation, Bug, SubArea-CoreText
