### ISSUE TITLE
Certificate file 'MyAPP_TemporaryKey.pfx' not found.

### ISSUE THREAD

**Issue by sssuourabh** [Microsoft/WinObjC#419] opened 2016-04-04 13:45 UTC

**Comment by asimonov-msft** [comment] 2016-04-19 15:17
This is a duplicate of Issue #231. The original issue has instructions for how to generate the file through VS.

**Closed by asimonov-msft** 2016-04-19 15:17 UTC
Labels: duplicate

**Comment by sssuourabh** [comment] 2016-04-20 07:05
thanks
