### ISSUE TITLE
(0.1 preview, Sep 6, 2016) Canabalt compile issue

### ISSUE THREAD

**Issue by DavidBurela** [Microsoft/WinObjC#997] opened 2016-09-12 13:37 UTC
Another regression in Canabalt. https://github.com/ericjohnson/canabalt-ios 
The rendering bug from #339 is gone, but music now works.

**Jan 14, 2016:** Compiiles. In game, SFX works but there is no music.

**Sep 6, 2016:** There is a compile error within the #define. 
canabalt-ios-master\flixel-ios\src\Flixel\FlxG.m
`result = AudioFileOpenURL(url, fsRdPerm, 0, &audioFileID);`

if you delete that line, and have the method just return; on the 1st line. Then it will compile and music works.

**Comment by rajsesh-msft** [comment] 2016-09-12 21:47
@DavidBurela we no longer define TARGET_OS_IOS.  What you want to do is change the code to:

#if TARGET_OS_IPHONE || WINOBJC
  result = AudioFileOpenURL(url, kAudioFileReadPermission, 0, &audioFileID);
#else
  result = AudioFileOpenURL(url, fsRdPerm, 0, &audioFileID);
#endif

it should work fine.  This is unfortunately by design as a result of our move to using Apple OSS core foundation.

**Comment by rajsesh-msft** [comment] 2016-09-22 22:13
@DavidBurela since this is by design as I mentioned above, I am closing this issue, please reopen if you disagree.

**Closed by rajsesh-msft** 2016-09-22 22:13 UTC
