### ISSUE TITLE
ScheduledTimerWithTimeInterval and ScheduledTimerWithTimeIntervalWithInvocation are failing on ARM

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#1702] opened 2017-01-13 18:35 UTC
ScheduledTimerWithTimeInterval and ScheduledTimerWithTimeIntervalWithInvocation are failing on ARM unit tests for develop debug builds.

The output for both is:
ScheduledTimerWithTimeInterval 
Value of: selectorCalledAsync.get()
Actual: 0
Expected: ((BOOL)1)
Which is: 1
FAILED: the scheduled timer did not call the method.

**Comment by msft-Jeyaram** [comment] 2017-01-20 22:08
Unable to reproduce.
The tests run fine on ARM and pass.

**Comment by ashvarma** [comment] 2017-01-23 18:27
We're seeing this fail in our recent lab run

**Comment by msft-Jeyaram** [comment] 2017-01-23 18:49
On this

**Comment by msft-Jeyaram** [comment] 2017-01-23 20:05
Still passing on ARM (Release/Debug).
Disabling the tests

[----------] 6 tests from NSTimer
[ RUN      ] NSTimer.NegativeTimeInterval
[       OK ] NSTimer.NegativeTimeInterval (1 ms)
[ RUN      ] NSTimer.ScheduledTimerWithTimeInterval
[       OK ] NSTimer.ScheduledTimerWithTimeInterval (201 ms)
[ RUN      ] NSTimer.ScheduledTimerWithTimeIntervalRepeat
[       OK ] NSTimer.ScheduledTimerWithTimeIntervalRepeat (602 ms)
[ RUN      ] NSTimer.ScheduledTimerWithTimeIntervalFireOnce
[       OK ] NSTimer.ScheduledTimerWithTimeIntervalFireOnce (0 ms)
[ RUN      ] NSTimer.ScheduledTimerWithTimeIntervalFireRepeat
[       OK ] NSTimer.ScheduledTimerWithTimeIntervalFireRepeat (502 ms)
[ RUN      ] NSTimer.ScheduledTimerWithTimeIntervalWithInvocation
[       OK ] NSTimer.ScheduledTimerWithTimeIntervalWithInvocation (200 ms)
[----------] 6 tests from NSTimer (1529 ms total)

**Comment by rajsesh-msft** [comment] 2017-01-23 20:40
Reactivating until fix is actually merged.

**Comment by msft-Jeyaram** [comment] 2017-01-23 22:00
Closing as per #1774

**Closed** 2017-01-23 22:00 UTC
Labels: Area-Foundation, Bug, Priority-Urgent
