### ISSUE TITLE
NSURLRequestNetworkServiceType undefined

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#140] opened 2015-09-04 23:56 UTC
NSURLRequestNetworkServiceType is undefined.  This is an argument to  NSMutableURLRequest -setNetworkServiceType:

**Comment by rajsesh-msft** [comment] 2015-11-09 23:35
This is a duplicate of issue #98 https://github.com/Microsoft/WinObjC/issues/98

**Closed** 2015-11-13 19:01 UTC
Labels: API request, Approved
