### ISSUE TITLE
There is a flicker in UIImageView when assigning new image to .image property

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#343] opened 2016-02-05 18:33 UTC
UIImageView shows short flicker between the images when new image is assigned with .image property. (Replacing existing image)

**Comment by Ramu-msft** [comment] 2016-02-24 14:30
This is a known issue #251.

**Comment by Ramu-msft** [comment] 2016-02-24 14:30
This is a duplicate of issue #251

**Closed by Ramu-msft** 2016-02-24 14:30 UTC
Labels: Under Review
