### ISSUE TITLE
unrecognised selector when defined in category

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#1589] opened 2016-12-19 15:40 UTC
W/Objective-C: -[_NSCFString JSONValue]: unrecognized selector in signature lookup.
E/WIL: C:\workspace\Windows\winobjc\Frameworks\Foundation\NSObject.mm(384)\(null)!0F9EED20: (caller: 0F9EEBAA) Objective-C Exception(1) tid(502c) 80070490 Element not found.
    Msg:[-[_NSCFString JSONValue]: unrecognized selector sent to instance 110E4760.] [_throwUnrecognizedSelectorException(HRESULT_FROM_WIN32(ERROR_NOT_FOUND))]

<CODE>
    NSString* json = [NSString stringWithContentsOfFile:aFileName encoding:NSUTF8StringEncoding error:nil];
    id o = [json JSONValue];
</CODE>

The definition and declaration are in the statically linked library

<declaration>
@interface NSString (NSString_SBJSON)
- (id)JSONFragmentValue;
- (id)JSONValue;
@end
</declaration>

<definition>
@implementation NSString (NSString_SBJSON)

- (id)JSONFragmentValue
{
    SBJsonParser *jsonParser = [SBJsonParser new];    
    id repr = [jsonParser fragmentWithString:self];    
    if (!repr)
        NSLog(@"-JSONFragmentValue failed. Error trace is: %@", [jsonParser errorTrace]);
    [jsonParser release];
    return repr;
}

- (id)JSONValue
{
    SBJsonParser *jsonParser = [SBJsonParser new];
    id repr = [jsonParser objectWithString:self];
    if (!repr)
        NSLog(@"-JSONValue failed. Error trace is: %@", [jsonParser errorTrace]);
    [jsonParser release];
    return repr;
}

@end
</definition>

**Comment by edvv** [comment] 2016-12-19 16:22
NSString is typically a class cluster, returning private classes from its constructors. Try this:

`NSLog(@"json: %@", json);`

and see the type of your receiver (which according to your error is an instance of _NSCFString).

i.e.: Don't use categories on a class cluster.

Sincerely,

Ed

**Comment by spalda2** [comment] 2016-12-19 17:26
I'm very sorry but this suggestion would break most of the several years perfectly working code on iOS. This bridge is supposed to be compatible with object C runtime and NOT the other way around. You suggestion denies the purpose of the whole thing. 

Moreover there's many class clusters in objective C and almost all of them have categories even in the SDK itself.

So I don't see this even as a workaround let alone a "fix" that should be done in the source code/

The actual instance type is whatever the runtime instantiates when calling [[NSString alloc] intxxx] the fact that it's  _NSCFString and therefore it doesn't see category on NSString is clearly the objective C runtime problem and it clearly makes your this bridge not compatible in one of the most crucial and useful features of objective C.

Regards
P

**Comment by rajsesh-msft** [comment] 2017-01-04 02:09
This is a dupe of #236. I just updated #236 with a workaround.  Hope that helps.

**Closed by rajsesh-msft** 2017-01-04 02:09 UTC
Labels: Area-Foundation
