### ISSUE TITLE
UILabels on Pori's about page do not wrap properly (20170407.8)

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#2573] opened 2017-04-19 21:31 UTC
![image](https://cloud.githubusercontent.com/assets/14316954/25203108/d2dcf2ca-250c-11e7-8455-629ce25b4134.png)

**Comment by rajsesh-msft** [comment] 2017-05-11 21:01
Dupe of #2572

**Closed by rajsesh-msft** 2017-05-11 21:01 UTC
Labels: Area-User Experience
