### ISSUE TITLE
Is something wrong when computing the runtime offsets for the ivars?

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1203] opened 2016-10-21 14:22 UTC
Dear WinObjC Engineers,

With winobjc v 0.2.160927:

Launch the samples > HelloUI project

Change the solution's property: Linker > System > SubSystem to "Console"

Launch the solution and this is printed to the console:

Warning: Class CABasicAnimation has first ivar _from with a negative offset of -4!

Does that warning indicate that there is something wrong when computing the runtime offsets for the ivars?

Sincerely,

Ed

**Comment by DHowett-MSFT** [comment] 2016-10-24 20:11
The negative offsets come from the compiler; I'm closing this as a dupe of #1208 since it has a self-contained repro.

**Closed by DHowett-MSFT** 2016-10-24 20:11 UTC
Labels: Area-Dev Tools, Bug
