### ISSUE TITLE
IntTypes.h unknown type name

### ISSUE THREAD

**Issue by gruve-p** [Microsoft/WinObjC#1521] opened 2016-12-12 11:10 UTC
I just installed the latest (0.2 161130 (November 30, 2016) ) version of the bridge. 
After I try import our open source Groestlwallet iOS project (https://github.com/Groestlcoin/groestlwallet) to UWP app using vsimporter, everything looks ok. But when I try build and run the UWP project, there are 26 errors show in my window:

![error](https://cloud.githubusercontent.com/assets/11212268/21097096/2d01429c-c063-11e6-8dad-8053498cde74.PNG)

Attached the build log for the context of what is happening:

[breadwallet.zip](https://github.com/Microsoft/WinObjC/files/645750/breadwallet.zip)

**Comment by memontic-ms** [comment] 2017-01-06 20:35
(Option 1) **Fix: Rename Groestlwallet's IntTypes.h file to something else.** (Recommended)
inttypes.h is a system header that is included from WinObjC's CoreFoundation.h header. In this case, CoreFoundation.h seems to be including Groestlwallet's IntTypes.h instead of the system header.

(Option 2) Conversely, a potential SDK change would be to modify the _sbclang.targets_ file to use -iquote instead of -I for project header maps. However, this _produces breaking changes for other projects_.
>     **The change below for sbclang.targets is not needed if you have renamed IntTypes.h**
>     <ItemGroup>
>       <ClangCompile>
>         <HeaderMapInclude Condition="'%(ClangCompile.HeaderMap)' == 'Project'">-iquote"$(ProjectHMapFilename).hmap"</HeaderMapInclude>
>         <HeaderMapInclude Condition="'%(ClangCompile.HeaderMap)' == 'Combined'">-I"$(CombinedHMapFilename).hmap"</HeaderMapInclude>
>       </ClangCompile>
>     </ItemGroup>

**Comment by gruve-p** [comment] 2017-01-09 10:50
Thank you for your kind reply.
I went for option 1 and renamed IntTypes.h to something else. I am getting now other errors:
![capture](https://cloud.githubusercontent.com/assets/11212268/21764111/b6aadb8e-d661-11e6-90a6-4ea325882cf5.PNG)

Are you able to build the application by renaming IntTypes.h to something else?

**Comment by gruve-p** [comment] 2017-02-17 13:57
Any updates on this?

**Comment by memontic-ms** [comment] 2017-04-27 22:20
@gruve-p I apologize for the long wait.

I was not able to reproduce the exact error you are seeing, but I did hit something similar while it compiled BRAppDelegate.m. It said that "cannot find protocol declaration for 'PKPushRegistryDelegate'" followed by and error saying "expected a type".

There have been quite a few changes since Feb 17th. It looks like the project you are trying out still has some errors during build, you can re-import the project again to see where it's at.

Since the initial question in this issue has been answered, I'm going to close this one out. You are welcome to open a new issue with further questions.

**Closed by memontic-ms** 2017-04-27 22:20 UTC
Labels: Area-Dev Tools, Bug, Triage-Investigate
