### ISSUE TITLE
UIFont - fontNamesForFamilyName should return real name instead of PostScript name

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#1029] opened 2016-09-23 00:36 UTC
Currently fontNamesForFamilyName returns system font's PostScript name. Many font file have different name for PostScript name and real name. Because of it, the name retrieved with fontNamesForFamilyName cannot be used to apply font, using fontWithName API. Fonts that have different PS and real name shows default font which is Segoe UI. Below screens are example from Typography Insight app - some of the fonts are displayed without problem since they happen to have same name for real name and PS name. I think fontNamesForFontFamilyName API should be updated to retrieve real font name instead of PostScript name.
Thanks!

***EDIT: This could be issue with fontWithName API, not fontNamesForFamilyName. fontWithName API could be updated to display correct font with PostScript name instead.**

Second image shows fonts that are displayed as Segoe UI fallback since names are incorrect.
![2016-09-22 17_01_10-typography insight2](https://cloud.githubusercontent.com/assets/13754172/18770474/16a6f792-80eb-11e6-909e-79180cb990a9.png)

Example of PostScript name and real name in Windows Font Viewer 
![2016-09-22 17_01_10-typography insight2a](https://cloud.githubusercontent.com/assets/13754172/18770479/29bf71a6-80eb-11e6-93fa-cd36f2aa7ea9.png)

![2016-09-22 17_01_10-typography insight3](https://cloud.githubusercontent.com/assets/13754172/18770628/fb15fe90-80ec-11e6-9e63-0a47a1312665.png)

**Comment by rajsesh-msft** [comment] 2016-09-23 18:24
@cre8ivepark take a look at our work in progress in the CT-DW branch.  We are moving all of core text over to using DWrite and in the process, @ms-jihua has changed the UIFont implementation to use DWrite.  This should very likely fix your issue.  We expect to merge these changes back to develop in October.

https://github.com/Microsoft/WinObjC/blob/CT-DW/Frameworks/UIKit/UIFont.mm
https://github.com/Microsoft/WinObjC/blob/CT-DW/Frameworks/CoreText/DWriteWrapper.mm

Please use #925 to track the progress of this work.

**Comment by rajsesh-msft** [comment] 2016-09-28 23:27
@cre8ivepark Closing this as duplicate of #925. Please let me know if that still doesn't work.

**Closed by rajsesh-msft** 2016-09-28 23:27 UTC
Labels: Area-Foundation

**Comment by cre8ivepark** [comment] 2016-09-28 23:47
@rajsesh-msft  Is it included in Sep 27 release?

**Comment by rajsesh-msft** [comment] 2016-09-28 23:58
@cre8ivepark this will be available in October release according to our current plan.  If you like, you can enlist in the CT-DW [branch ](https://github.com/Microsoft/WinObjC/blob/CT-DW/)and get an early preview of this.

**Comment by cre8ivepark** [comment] 2016-09-29 00:09
@rajsesh-msft  Thanks Rajesh, I would like to try it. When I try checking out CT-DW branch, it gives me following errors with long list of files. Should I use different git command?

PS F:\WinObjC> git checkout CT-DW
error: The following untracked working tree files would be overwritten by c
        .ci-repo.xml
        .clang-format
        .gitattributes
        .gitignore
        .gitmodules
        Frameworks/AVFoundation/AVAsset.mm
        Frameworks/AVFoundation/AVAssetExportSession.mm
        Frameworks/AVFoundation/AVAssetImageGenerator.mm
        Frameworks/AVFoundation/AVAssetReader.mm
        Frameworks/AVFoundation/AVAssetReaderAudioMixOutput.mm
        Frameworks/AVFoundation/AVAssetReaderOutput.mm
        Frameworks/AVFoundation/AVAssetReaderOutputMetadataAdaptor.mm
        Frameworks/AVFoundation/AVAssetReaderSampleReferenceOutput.mm
        Frameworks/AVFoundation/AVAssetReaderTrackOutput.mm
 ...

**Comment by rajsesh-msft** [comment] 2016-09-29 18:20
git checkout -b CT-dw origin/CT-dw should do it, if you already have it cloned from github develop.
