### ISSUE TITLE
NSCalendar tests have many deprecation warnings when built on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#743] opened 2016-08-01 18:46 UTC
These stuck out in particular among the build warnings, just due to volume:

Foundation/NSCalendarTests.mm:449:31: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.era, NSUndefinedDateComponent);
                              ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:450:32: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.year, NSUndefinedDateComponent);
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:451:33: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.month, NSUndefinedDateComponent);
                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:452:34: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.second, NSUndefinedDateComponent);
                                 ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:453:38: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.nanosecond, NSUndefinedDateComponent);
                                     ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:454:26: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
Foundation/NSCalendarTests.mm:454:26: warning: 'setWeek:' is deprecated: first deprecated in OS X 10.9 - Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:437:1: note: 'setWeek:' has been explicitly marked deprecated here
- (void)setWeek:(NSInteger)v NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean");
^
Foundation/NSCalendarTests.mm:454:26: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
Foundation/NSCalendarTests.mm:454:26: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
Foundation/NSCalendarTests.mm:454:26: warning: 'setWeek:' is deprecated: first deprecated in OS X 10.9 - Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:437:1: note: 'setWeek:' has been explicitly marked deprecated here
- (void)setWeek:(NSInteger)v NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean");
^
Foundation/NSCalendarTests.mm:454:32: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:454:26: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(components.week, NSUndefinedDateComponent);
                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
Foundation/NSCalendarTests.mm:455:35: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.weekday, NSUndefinedDateComponent);
                                  ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:456:42: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.weekdayOrdinal, NSUndefinedDateComponent);
                                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:457:35: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.quarter, NSUndefinedDateComponent);
                                  ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:458:39: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.weekOfMonth, NSUndefinedDateComponent);
                                      ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:459:38: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.weekOfYear, NSUndefinedDateComponent);
                                     ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:460:45: warning: 'NSUndefinedDateComponent' is deprecated: first deprecated in OS X 10.10 - Use NSDateComponentUndefined instead [-Wdeprecated-declarations]
    ASSERT_EQ(components.yearForWeekOfYear, NSUndefinedDateComponent);
                                            ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:411:2: note: 'NSUndefinedDateComponent' has been explicitly marked deprecated here
        NSUndefinedDateComponent NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSDateComponentUndefined instead") = NSDateComponentUndefined
        ^
Foundation/NSCalendarTests.mm:467:16: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    components.week = 3;
               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
Foundation/NSCalendarTests.mm:467:16: warning: 'setWeek:' is deprecated: first deprecated in OS X 10.9 - Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean [-Wdeprecated-declarations]
    components.week = 3;
               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:437:1: note: 'setWeek:' has been explicitly marked deprecated here
- (void)setWeek:(NSInteger)v NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean");
^
Foundation/NSCalendarTests.mm:467:16: warning: 'setWeek:' is deprecated: first deprecated in OS X 10.9 - Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean [-Wdeprecated-declarations]
    components.week = 3;
               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:437:1: note: 'setWeek:' has been explicitly marked deprecated here
- (void)setWeek:(NSInteger)v NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean");
^
Foundation/NSCalendarTests.mm:475:61: warning: 'NSWeekCalendarUnit' is deprecated: first deprecated in OS X 10.10 - Use NSCalendarUnitWeekOfMonth or NSCalendarUnitWeekOfYear, depending on which you mean [-Wdeprecated-declarations]
    NSDateComponents* weekComponents = [calendar components:NSWeekCalendarUnit fromDate:date];
                                                            ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:71:2: note: 'NSWeekCalendarUnit' has been explicitly marked deprecated here
        NSWeekCalendarUnit NS_CALENDAR_ENUM_DEPRECATED(10_4, 10_10, 2_0, 8_0, "Use NSCalendarUnitWeekOfMonth or NSCalendarUnitWeekOfYear, depending on which you mean") = kCFCalendarUnitWeek,
        ^
Foundation/NSCalendarTests.mm:477:33: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(3, weekComponents.week);
                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
Foundation/NSCalendarTests.mm:477:33: warning: 'setWeek:' is deprecated: first deprecated in OS X 10.9 - Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(3, weekComponents.week);
                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:437:1: note: 'setWeek:' has been explicitly marked deprecated here
- (void)setWeek:(NSInteger)v NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use setWeekOfMonth: or setWeekOfYear:, depending on which you mean");
^
Foundation/NSCalendarTests.mm:477:33: warning: 'week' is deprecated: first deprecated in OS X 10.9 - Use weekOfMonth or weekOfYear, depending on which you mean [-Wdeprecated-declarations]
    ASSERT_EQ(3, weekComponents.week);
                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h:436:1: note: 'week' has been explicitly marked deprecated here
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");
^
25 warnings generated.

**Comment by rajsesh-msft** [comment] 2016-08-08 18:43
Dupe of #683

**Closed by rajsesh-msft** 2016-08-08 18:43 UTC
Labels: Area-Foundation, Bug
