### ISSUE TITLE
Canabalt [x86]: Missing button text

### ISSUE THREAD

**Issue by MichelLopez** [Microsoft/WinObjC#1491] opened 2016-12-01 21:19 UTC
Desktop running 1491

Run the app (debug/release)

Expected: App runs, shows buttons after splash screen appears.
Actual: App runs, but missing button text

**Comment by rajsesh-msft** [comment] 2016-12-01 21:21
This is a duplicate of #924.

**Closed by rajsesh-msft** 2016-12-01 21:21 UTC
Labels: Resolution-Duplicate
