### ISSUE TITLE
Foundation NSTimeZone knownTimeZoneNames does not map to Windows time zones

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#304] opened 2016-01-11 22:22 UTC
In implementing code where Foundation *NSTimeZone knownTimeZoneNames* is utilized, the return value is expected to be an NSArray of NSString values. In the apple ecosystem, this array holds 426 values (format: @"Africa/Accra"). 

The values being returned at present by VS are an array of NSObjects - inspectable values appear to be void pointers if one inspects it via *Locals* window.

**Comment by antoine-haas** [comment] 2016-02-26 21:26
This is due to the current VS debugging tools, which don't properly display Objective-C objects. We are working on improving the Objective-C debug experience, specifically for NSArray which seems to be the cause of your problem. Stay tuned for more updates on this.

**Comment by antoine-haas** [comment] 2016-04-04 21:25
This has been fixed with Visual Studio Update 2: if you install the update and inspect the value returned by the _knownTimeZoneNames_  method in the debugger _Locals_ or _Watch_ windows, it will be properly displayed as an array of NSString values. However, note that 168 values will be returned by the Windows Bridge for IOS implementation of the method to match the time zones Windows provide, instead of the 467 values returned by Apple's implementation.

**Closed by antoine-haas** 2016-04-04 21:25 UTC
Labels: Under Review
