### ISSUE TITLE
Address performance issues due to WARP device being loaded/unloaded many times

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1846] opened 2017-01-27 01:56 UTC

**Comment by rajsesh-msft** [comment] 2017-01-27 02:08
@DHowett-MSFT, this is the perf issue you were telling me about today.

**Comment by DHowett-MSFT** [comment] 2017-02-07 23:46
This is unreproduceable since the merge of CGD2D into develop. We believe that creating one factory per render target in the CGGraphicBufferImage code, instead of one factory per application launch, was causing the device reference to be destroyed every time a renderer went out of scope.

**Closed by DHowett-MSFT** 2017-02-07 23:46 UTC
Labels: Area-Foundation, SubArea-CoreGraphics, Task, Triage-Approved for Fix
