### ISSUE TITLE
Cannot create object for MFMailComposeViewController

### ISSUE THREAD

**Issue by SivaguruElangovan** [Microsoft/WinObjC#452] opened 2016-04-22 12:42 UTC
Error: no known class method for selector 'alloc'

Getting above while creating object for MFMailComposeViewController
MFMailComposeViewController *mailViewController = [[MFMailComposeViewController alloc] init];

**Comment by SNanjappa** [comment] 2016-04-25 13:51
@SivaguruElangovan Even i am facing the same issue, did you find any way to solve the issue? 
@winobjc-bot

**Comment by ArnOmsft** [comment] 2016-05-13 00:39
This is a duplicate of #327. We do not currently have support for MFMailComposeViewController but we added this to our backlog (cf. #327).
Closing this one.

**Closed by ArnOmsft** 2016-05-13 00:39 UTC
Labels: Under Review
