### ISSUE TITLE
https://dev.windows.com/en-us/bridges/ios#vms - windows login password needed

### ISSUE THREAD

**Issue by lux2911** [Microsoft/WinObjC#317] opened 2016-01-18 17:06 UTC
Please, give us passwords for VM images at https://dev.windows.com/en-us/bridges/ios#vms

Thank you!

**Comment by antoine-haas** [comment] 2016-01-18 18:27
This is a duplicate of #311

**Closed** 2016-01-19 17:46 UTC
Labels: duplicate
