### ISSUE TITLE
UIWebView stringByEvaluatingJavaScriptFromString causes runtime error

### ISSUE THREAD

**Issue by segadude** [Microsoft/WinObjC#582] opened 2016-06-23 21:26 UTC
I use the following piece of code to get the page title from the UIWebView in my browser application:

`[webView stringByEvaluatingJavaScriptFromString:@"document.title"];`

This is executed when the UIWebView finishes loading, in the `webViewDidFinishLoad:` method. When this line executes, I get a `UNSException`, which leads to the app crashing. If I comment out this line, the app runs fine. The relevant lines from the log are below:

```

Exception thrown at 0x7492DAE8 in appname.exe: Microsoft C++ exception: Js::JavascriptExceptionObject at memory location 0x092CE4CC.
Exception thrown at 0x7492DAE8 in appname.exe: Microsoft C++ exception: Js::JavascriptExceptionObject at memory location 0x092CE95C.
Exception thrown at 0x7492DAE8 in appname.exe: Microsoft C++ exception: UNSException at memory location 0x092CB8DC.
The thread 0x3534 has exited with code 0 (0x0).
Unhandled exception at 0x7492DAE8 in appname.exe: Microsoft C++ exception: UNSException at memory location 0x092CB8DC.
```

This happens with the latest 0.1 Preview (June 21, 2016) release, but I've also had this issue with all the previous releases I've tried. 

[stringByEvaluatingJavaScriptFromString documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/#//apple_ref/occ/instm/UIWebView/stringByEvaluatingJavaScriptFromString:)

**Comment by tadam-msft** [comment] 2016-12-15 00:34
Resolving as duplicate of #988

**Closed by tadam-msft** 2016-12-15 00:34 UTC
Labels: Area-User Experience, Resolution-Duplicate
