### ISSUE TITLE
CoreGraphics [PDF] Blending mode tests fail on ARM

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#2284] opened 2017-03-21 01:54 UTC
> Non-passing Tests:
 
    AdobePDFBlendModes_CGContextBlendMode::Test [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/0 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/1 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/2 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/3 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/4 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/5 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/6 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/7 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/8 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/9 [Failed]
       AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/10 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/11 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/12 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/13 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/14 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/15 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/16 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/17 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/18 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/19 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/20 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/21 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/22 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/23 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/24 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/25 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/26 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/27 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/28 [Failed]
        AdobePDFBlendModes_CGContextBlendMode.OverlappedRects/29 [Failed]
    AdobePDFBlendModes_CGContextBlendModeImage::Test [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/0 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/1 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/2 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/4 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/5 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/6 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/7 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/8 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/9 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/10 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/11 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/12 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/13 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsSource/14 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/0 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/1 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/2 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/3 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/4 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/5 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/6 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/7 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/8 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/9 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/10 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/11 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/12 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/13 [Failed]
        AdobePDFBlendModes_CGContextBlendModeImage.ImageAsDestination/14 [Failed]
    NSLogging_NSLoggingWideBasicTests::Test [Failed]
    NSLogging_NSLoggingNSStringBasicTests::Test [Failed]
    NSLogging_NSLoggingWideFormatTests::Test [Failed]
    NSLogging_NSLoggingNSStringFormatTests::Test [Failed]
    NSLogging_NSLogTests::Test [Failed]

**Comment by aballway** [comment] 2017-03-21 16:33
Are the NSLogging failures related to this, or should those be in a separate issue?

**Comment by pradipd** [comment] 2017-03-21 16:36
This is failing on desktop for me.
And in the labs on a consistent basis.

Repro:
init.cmd
.tools\nuget restore build\build.sln
msbuild /p:configuration=debug /p:platform=x86 build\build.sln
<powershell> run-unitests.ps1

**Comment by msft-Jeyaram** [comment] 2017-03-21 19:08
@DHowett-MSFT indicated that he ran them locally and the tests passed.

Seeing the outputs, it looks like our image diff might not be doing it's job.
Investigating further.
Expected:

![000001_ endmode overlappedrects_0_testimage cgcontext blending_kcgblendmodemultiply](https://cloud.githubusercontent.com/assets/18413092/24126957/53c2ef98-0d8e-11e7-8b51-cac79d1926c3.png)


Rendered:
![000002_ endmode overlappedrects_0_testimage cgcontext blending_kcgblendmodemultiply](https://cloud.githubusercontent.com/assets/18413092/24126959/598ffd80-0d8e-11e7-8770-aeac3378960f.png)


Diff:
![000003_ endmode overlappedrects_0_greenline testimage cgcontext blending_kcgblendmodemultiply](https://cloud.githubusercontent.com/assets/18413092/24126960/5d1bbce6-0d8e-11e7-8a11-f64358f4cb45.png)

**Comment by aballway** [comment] 2017-03-21 19:16
It's also quite possible that the hues of the colors are marginally off.  Possibly some rounding issue somewhere.

**Comment by msft-Jeyaram** [comment] 2017-03-21 19:58
The root cause is the build version differences, looks like in the incremental build, there are few changes to the rendered pixel values.

This is the reason we are seeing the failures on some user's machines (who are running the incremental version) vs the others/labs (who are running the older version)

**Comment by msft-Jeyaram** [comment] 2017-03-21 20:04
The root cause is the different versions of windows that are being used. looks like in the latest version, there are few changes to the rendered pixel values.

This is the reason we are seeing the failures on some user's machines (who are running the latest version of windows) vs the others/labs (who are running the current version)

**Comment by msft-Jeyaram** [comment] 2017-03-21 20:07
Due to the nature of this bug (release blocking), we should be using the current version of windows. When we upgrade to the next version of windows, we will at various ways to fix/prevent these forms of errors.

**Comment by rajsesh-msft** [comment] 2017-03-21 21:25
Reactivating as we will likely hit it when we move to the new insider train.  We will keep this issue to recreate reference images.  Not blocking issue anymore though.

**Comment by DHowett-MSFT** [comment] 2017-04-05 18:50
This bug was caused by a change in the Windows insider rings. In short, images rasterized using the software "GPU" device will differ slightly across versions due to a precision change in some emulated shaders.

This is being tracked internally. We will likely need to regenerate our test images when the WARP pipeline changes are finalized.

**Comment by rajsesh-msft** [comment] 2017-06-21 02:32
Since this is tracked internally.  We can regenerate the images as needed, for now resolving this issue.

**Closed by rajsesh-msft** 2017-06-21 02:32 UTC
Labels: Area-Foundation, Bug, Resolution-Won’t Fix, SubArea-CoreGraphics
