### ISSUE TITLE
Crash with std::vector as second parameter in method 

### ISSUE THREAD

**Issue by sakrist** [Microsoft/WinObjC#1312] opened 2016-11-03 14:59 UTC
```
- (void) testMethod {
	std::vector<int> testInts;
	testInts.push_back(1);
	[self reciveVector:testInts andObject:self];
}

// Crash
- (void) reciveVector:(std::vector<int>)testInts andObject:(id)object {
	NSLog(@"%d", testInts.size());
}
```
Looks like it's trying do retain for vector
```
 LIBOBJC2.DLL!retain(objc_object * obj) Line 192	Objective-C
 LIBOBJC2.DLL!objc_retain(objc_object * obj) Line 459	Objective-C
 LIBOBJC2.DLL!objc_storeStrong(objc_object * * addr, objc_object * value) Line 487	Objective-C
```

If method will receive just one property with std::vector, then no crash.

Also if I use pointer on vector, it works.
```
- (void) testMethod {
	std::vector<int> testInts;
	testInts.push_back(1);
	[self reciveVector:&testInts andObject:self];
}

// Works
- (void) reciveVector:(std::vector<int> *)testInts andObject:(id)object {
	NSLog(@"%d", testInts->size());
}
```

@3D4Medical

**Comment by DHowett-MSFT** [comment] 2016-11-03 15:50
Hi @sakrost,
Thanks for the report!

This is a duplicate of #1140.

Feel free to pile onto that issue or speak up if it doesn't sound like the same root cause.

**Comment by bbowman** [comment] 2016-11-03 18:43
@DHowett-MSFT should we be closing issues that are duplicates

**Comment by DHowett-MSFT** [comment] 2016-11-03 18:44
Yep, sorry!

**Closed by DHowett-MSFT** 2016-11-03 18:44 UTC

**Comment by sakrist** [comment] 2016-11-03 20:47
Cool, thanks. 
Was not sure if it was duplicate, because mine gives little more details.
