### ISSUE TITLE
Is there a support react native?

### ISSUE THREAD

**Issue by bbayraktutar** [Microsoft/WinObjC#567] opened 2016-06-21 02:38 UTC
I get this error 'RCTRootView.h' file not found	. 
Is there a support react native?

**Comment by rajsesh-msft** [comment] 2016-06-21 16:48
This is a duplicate of #397 - react native should now support native UWPs without requiring the islandwood bridge.  Have you looked at this [blog](https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/)?

**Comment by rajsesh-msft** [comment] 2016-06-22 00:37
Closing this issue as dupe of #397

**Closed by rajsesh-msft** 2016-06-22 00:37 UTC

**Comment by bbayraktutar** [comment] 2016-06-22 00:55
I keep getting the same error
