### ISSUE TITLE
CoreText drawing non-ASCII characters incorrectly

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#1094] opened 2016-10-06 12:26 UTC
Using the following code to draw the sample text containing non-ASCII characters using CoreText with the 0.2.160927 SDK release, we can see the following drawing behavior: The two ASCII letters "a" and "z" are drawn, followed by one or two random characters or boxes (e.g. "azò" or "az☐☐").

```objc
NSString *text = @"a中國人z";

CGMutablePathRef path = CGPathCreateMutable();
CGPathAddRect(path, NULL, CGRectMake(0, 0, 500, 500));

CGColorRef myCGColor = [UIColor blackColor].CGColor;
CTFontRef myCFFont = CTFontCreateWithName((__bridge CFStringRef)@"Helvetica", 20, NULL);
NSDictionary *attributesDict = @{(id)kCTFontAttributeName: (id)myCFFont,
                                 (id)kCTForegroundColorAttributeName: (id)myCGColor};

CFAttributedStringRef attrString = CFAttributedStringCreate(kCFAllocatorDefault, (__bridge CFStringRef)text, (__bridge CFDictionaryRef)attributesDict);
CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString(attrString);
CTFrameRef frame = CTFramesetterCreateFrame(framesetter, CFRangeMake(0, 0), path, NULL);
CFArrayRef lines = CTFrameGetLines(frame);
CTLineRef line = (CTLineRef)CFArrayGetValueAtIndex(lines, 0);

CTLineDraw(line, context);
```

**Comment by aballway** [comment] 2016-10-06 16:41
This is actually an issue that's been resolved on another branch.  We're doing an overhaul of CoreText in the CT-DW branch, so this will be working properly once those changes get merged into master.

**Comment by rajsesh-msft** [comment] 2016-10-13 22:30
Resolving it as duplicate of #925.

**Closed** 2016-10-13 22:31 UTC
Labels: Area-Foundation, Bug, duplicate, SubArea-CoreText
