### ISSUE TITLE
Compiler include error

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#996] opened 2016-09-12 13:06 UTC
Dear WinObjC Engineers,

While working on a large WinObjC port, I ran into a #include bug related to the way custom foundation classes are arranged in the file structure of the project. I isolated the problem into a small test project and have included it with this post. Can you please run vsimporter.exe on the ierror.xcodeproj file [bundle] and then compile the resulting solution to produce the compiler error and then let me know how to work around this issue (without rearranging files or removing the include path in the solution properties; or reordering the include statements). See the MyClass.m file for details on the bug.

Sincerely,

Ed

[ierror.zip](https://github.com/Microsoft/WinObjC/files/467347/ierror.zip)

**Comment by edvv** [comment] 2016-09-20 12:14
Is there an update on this issue? Feel free to contact me offline at ed@vvi.com if needed.

**Comment by edvv** [comment] 2016-10-05 13:59
The workaround is to #import <Foundation/Foundation.h> in MyClass.h - and in the larger project import that into the root class of the object graph. That may be why this issue does not show up in other projects (as people often import a cover header first off and rely upon PCH for optimization). This is not good for limited scoping of header files, but it does provide a mainstream workaround.

Also, the problem does not appear specific to defining an additional system header directory for search purposes, as initially hypothesized.

**Comment by bbowman** [comment] 2016-10-28 18:53
Discussed with @mukhole and this appears to be a duplicate of issue 456. Closing this one and hopefully @edvv can track the original for a fix.

https://github.com/Microsoft/WinObjC/issues/456

**Closed by bbowman** 2016-10-28 18:53 UTC
Labels: Area-Foundation, Bug, Triage-Investigate
