### ISSUE TITLE
Blit basic untransformed images to CGD2DContext

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1078] opened 2016-10-04 17:56 UTC
Depends on #1072 and #1070.

**Comment by DHowett-MSFT** [comment] 2016-11-01 21:58
This is on @msft-Jeyaram now, IIRC?

**Comment by rajsesh-msft** [comment] 2016-11-01 22:34
@DHowett-MSFT yes, this is a dupe of #1235

**Closed by rajsesh-msft** 2016-11-01 22:34 UTC
Labels: Area-Foundation, Task, Triage-Approved for Fix
