### ISSUE TITLE
[NSPredicate predicateWithFormat:] does not correctly match if rhs bool value is defined in format string.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#541] opened 2016-06-09 13:21 UTC
NSPredicate does not match a bool property if the rhs value is specified in the format string. However if the rhs value is supplied as a param it does work as expected.

For example:

```
TestObjectB *b = [[TestObjectB alloc] init];
b.flag = YES;

[[NSPredicate predicateWithFormat:@"flag == YES"] evaluateWithObject:b] // Will be false
[[NSPredicate predicateWithFormat:@"flag == %d", YES] evaluateWithObject:d] // Will be true
```

Another twist is that if you match against a NSDictionary object it works as expected:

```
NSDictionary *d = @{@"flag" : @(YES)};

[[NSPredicate predicateWithFormat:@"flag == YES"] evaluateWithObject:d]) // Will be true
```

**Comment by msft-Jeyaram** [comment] 2016-06-09 17:01
@rupertdaniel  thank you for filing the issue.
The root cause has been tracked down and it turns out to be, the changes we made to NSNumber isEqual in the new CoreFoundation.

**Comment by ArnOmsft** [comment] 2016-07-19 15:10
This was part of our release on June 21. Closing.

**Closed by ArnOmsft** 2016-07-19 15:10 UTC
Labels: Coming Soon
